# Generated by Django 4.0.3 on 2022-03-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('', 'Select One'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=15)),
                ('description', models.TextField(max_length=500)),
                ('on_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
